//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.11.2
//     from Assets/InputSystem/MainControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @MainControls: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @MainControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""MainControls"",
    ""maps"": [
        {
            ""name"": ""MainActionMap"",
            ""id"": ""a4e4b131-e81b-4d9f-b976-3578178b0cb1"",
            ""actions"": [
                {
                    ""name"": ""MoveView"",
                    ""type"": ""Button"",
                    ""id"": ""ea3b721f-743b-4b5a-99a5-5b3018e93120"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateViewClockwise"",
                    ""type"": ""Button"",
                    ""id"": ""3943e45d-b3b8-4708-9b8f-a3b454344465"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RotateViewCounterclockwise"",
                    ""type"": ""Button"",
                    ""id"": ""af959950-3f89-48aa-8232-526025e059a4"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Zoom"",
                    ""type"": ""Value"",
                    ""id"": ""1ad8db9f-2e9e-4776-93ec-a15e0febb080"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""950c0f5f-e194-4205-9884-a7e88de221f9"",
                    ""path"": ""<Mouse>/middleButton"",
                    ""interactions"": ""Press(behavior=2)"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MoveView"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ecd5edf8-08c5-4950-ab53-3f461b04f6ef"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateViewClockwise"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7a884862-c09b-4c35-8a9d-11200226d2bf"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RotateViewCounterclockwise"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3b969575-e5d6-4b54-a560-927161601523"",
                    ""path"": ""<Mouse>/scroll"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Zoom"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // MainActionMap
        m_MainActionMap = asset.FindActionMap("MainActionMap", throwIfNotFound: true);
        m_MainActionMap_MoveView = m_MainActionMap.FindAction("MoveView", throwIfNotFound: true);
        m_MainActionMap_RotateViewClockwise = m_MainActionMap.FindAction("RotateViewClockwise", throwIfNotFound: true);
        m_MainActionMap_RotateViewCounterclockwise = m_MainActionMap.FindAction("RotateViewCounterclockwise", throwIfNotFound: true);
        m_MainActionMap_Zoom = m_MainActionMap.FindAction("Zoom", throwIfNotFound: true);
    }

    ~@MainControls()
    {
        UnityEngine.Debug.Assert(!m_MainActionMap.enabled, "This will cause a leak and performance issues, MainControls.MainActionMap.Disable() has not been called.");
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // MainActionMap
    private readonly InputActionMap m_MainActionMap;
    private List<IMainActionMapActions> m_MainActionMapActionsCallbackInterfaces = new List<IMainActionMapActions>();
    private readonly InputAction m_MainActionMap_MoveView;
    private readonly InputAction m_MainActionMap_RotateViewClockwise;
    private readonly InputAction m_MainActionMap_RotateViewCounterclockwise;
    private readonly InputAction m_MainActionMap_Zoom;
    public struct MainActionMapActions
    {
        private @MainControls m_Wrapper;
        public MainActionMapActions(@MainControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @MoveView => m_Wrapper.m_MainActionMap_MoveView;
        public InputAction @RotateViewClockwise => m_Wrapper.m_MainActionMap_RotateViewClockwise;
        public InputAction @RotateViewCounterclockwise => m_Wrapper.m_MainActionMap_RotateViewCounterclockwise;
        public InputAction @Zoom => m_Wrapper.m_MainActionMap_Zoom;
        public InputActionMap Get() { return m_Wrapper.m_MainActionMap; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MainActionMapActions set) { return set.Get(); }
        public void AddCallbacks(IMainActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_MainActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MainActionMapActionsCallbackInterfaces.Add(instance);
            @MoveView.started += instance.OnMoveView;
            @MoveView.performed += instance.OnMoveView;
            @MoveView.canceled += instance.OnMoveView;
            @RotateViewClockwise.started += instance.OnRotateViewClockwise;
            @RotateViewClockwise.performed += instance.OnRotateViewClockwise;
            @RotateViewClockwise.canceled += instance.OnRotateViewClockwise;
            @RotateViewCounterclockwise.started += instance.OnRotateViewCounterclockwise;
            @RotateViewCounterclockwise.performed += instance.OnRotateViewCounterclockwise;
            @RotateViewCounterclockwise.canceled += instance.OnRotateViewCounterclockwise;
            @Zoom.started += instance.OnZoom;
            @Zoom.performed += instance.OnZoom;
            @Zoom.canceled += instance.OnZoom;
        }

        private void UnregisterCallbacks(IMainActionMapActions instance)
        {
            @MoveView.started -= instance.OnMoveView;
            @MoveView.performed -= instance.OnMoveView;
            @MoveView.canceled -= instance.OnMoveView;
            @RotateViewClockwise.started -= instance.OnRotateViewClockwise;
            @RotateViewClockwise.performed -= instance.OnRotateViewClockwise;
            @RotateViewClockwise.canceled -= instance.OnRotateViewClockwise;
            @RotateViewCounterclockwise.started -= instance.OnRotateViewCounterclockwise;
            @RotateViewCounterclockwise.performed -= instance.OnRotateViewCounterclockwise;
            @RotateViewCounterclockwise.canceled -= instance.OnRotateViewCounterclockwise;
            @Zoom.started -= instance.OnZoom;
            @Zoom.performed -= instance.OnZoom;
            @Zoom.canceled -= instance.OnZoom;
        }

        public void RemoveCallbacks(IMainActionMapActions instance)
        {
            if (m_Wrapper.m_MainActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMainActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_MainActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MainActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MainActionMapActions @MainActionMap => new MainActionMapActions(this);
    public interface IMainActionMapActions
    {
        void OnMoveView(InputAction.CallbackContext context);
        void OnRotateViewClockwise(InputAction.CallbackContext context);
        void OnRotateViewCounterclockwise(InputAction.CallbackContext context);
        void OnZoom(InputAction.CallbackContext context);
    }
}
